[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.4.0"
figment = { version = "0.10.8", features = ["json", "toml", "env"] }
serde = { version = "1.0.159", features = ["derive", "rc"] }
serde_json = "1.0.95"
streaming = { path = "../streaming" }
tokio = { version = "1.26.0", features = ["full"] }
clap = { version = "4.1.11", features = ["derive"] }
tracing = { version = "0.1.37"}
tracing-subscriber = {version = "0.3.16"}
chrono = "0.4.24"
anyhow = "1.0.70"
tokio-graceful-shutdown = "0.12.1"
ctrlc = "3.2.5"
