[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = { path = "../shared" }
streaming = { path = "../streaming" }
bytes = "1.4.0"
figment = { version = "0.10.8", features = ["json", "toml", "env"] }
flume = "0.10.14"
thiserror = "1.0.40"
serde = { version = "1.0.159", features = ["derive", "rc"] }
serde_json = "1.0.95"
tokio = { version = "1.26.0", features = ["full"] }
clap = { version = "4.1.11", features = ["derive"] }
tracing = { version = "0.1.37"}
tracing-subscriber = {version = "0.3.16"}
chrono = "0.4.24"
anyhow = "1.0.70"
tokio-graceful-shutdown = "0.12.1"
ctrlc = "3.2.5"
rcgen = "0.10.0"
quinn = "0.10.0"
rustls = { version = "0.21.1", features = ["dangerous_configuration", "quic"] }

[features]
allow_kill_command = []
