[http]
enabled = true
address = "0.0.0.0:3000"

[http.cors]
enabled = true
allowed_methods = [ "GET", "POST", "PUT", "DELETE" ]
allowed_origins = [ "*" ]
allowed_headers = [ ]
exposed_headers = [ ]
allow_credentials = false
allow_private_network = false

[http.tls]
enabled = false
cert_file = "certs/iggy_cert.pem"
key_file = "certs/iggy_key.pem"

[tcp]
enabled = true
address = "0.0.0.0:8090"

[tcp.tls]
enabled = false
certificate = "certs/iggy.pfx"
password = "iggy123"

[quic]
enabled = true
address = "0.0.0.0:8080"
max_concurrent_bidi_streams = 10_000
datagram_send_buffer_size = 100_000
initial_mtu = 8_000
send_window = 100_000
receive_window = 100_000
keep_alive_interval = 5_000
max_idle_timeout = 10_000

[message_saver]
enabled = true
enforce_sync = true
interval = 30

[system]
path = "local_data"

[system.stream]
path = "streams"

[system.stream.topic]
path = "topics"

[system.stream.topic.partition]
path = "partitions"
deduplicate_messages = false
enforce_sync = false
validate_checksum = false
messages_required_to_save = 10_000
messages_buffer = 1_048_576

[system.stream.topic.partition.segment]
size_bytes = 1_000_000_000
cache_indexes = true
cache_time_indexes = true
