[package]
name = "sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = { path = "../shared" }
async-trait = "0.1.68"
bytes = "1.4.0"
reqwest = { version = "0.11.18", features = ["json"] }
reqwest-middleware = "0.2.2"
reqwest-retry = "0.2.2"
serde = { version = "1.0.159", features = ["derive", "rc"] }
serde_json = "1.0.95"
serde_with = { version = "3.0.0", features = ["base64"] }
thiserror = "1.0.40"
tokio = { version = "1.28.2", features = ["full"] }
tracing = { version = "0.1.37"}
tracing-subscriber = {version = "0.3.16"}
quinn = "0.10.0"
rustls = { version = "0.21.1", features = ["dangerous_configuration", "quic"] }
