[package]
name = "sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
streaming = { path = "../streaming" }
thiserror = "1.0.40"
tokio = { version = "1.26.0", features = ["full"] }
tracing = { version = "0.1.37"}
tracing-subscriber = {version = "0.3.16"}
